### ISSUE TITLE
Benutzer soll sich anmelden können

### ISSUE THREAD

**Issue by Bouchra-Allachi** [Bedrohung-der-Bienen/Transformationsfelder-Digitalisierung#1]
# Szenario:  Benutzer soll sich anmelden können
- **Gegeben** Der Benutzer ist auf der Startseite angelangt
- **Wenn** sich der Benutzer anmelden möchte
- **Dann** klickt er auf den Login Tab in der Navigation
- **Und** es öffnet sich eine Anmeldeseite
- **Und** der Benutzer meldet sich mit seinem E-Mail und Passwort an

Der Benutzer muss die Möglichkeit haben sich anmelden zu können, um Kommentare hinzuzufügen, eine Pflanze bewerten zu können  und seine  Favoritenliste einsehen zu können.
-----

__Als__ Benutzer,
__möchte ich__ mich anmelden können,
__damit__ ich alle Funktionen der Webseite in vollen Umfang nutzen kann.

__Szenario 1__: Benutzer kann sich anmelden.
__Szenario 2__: Anmeldung schlägt fehl.

**Comment by Bouchra-Allachi** [comment]
> 
> 
> Der Benutzer muss die Möglichkeit haben sich anmelden zu können, um Kommentare hinzuzufügen, eine Pflanze bewerten zu können und seine Favoritenliste einsehen zu können.

**Comment by Moosgloeckchen** [comment]
__Szenario 1__: Der Benutzer meldet sich erfolgreich an.
__Szenario 2__: Die Anmeldung schlägt fehl, weil die Anmeldedaten nicht korrekt sind
__Szenario 3__: Die Anmeldung schlägt fehl weil dieses Konto nicht existiert, dann soll die Registrierung folgen.
