### ISSUE TITLE
Eine Navbar mit Icons soll erstellt werden

### ISSUE THREAD

**Issue by Bouchra-Allachi** [Bedrohung-der-Bienen/Transformationsfelder-Digitalisierung#14]
# Szenario:  Der Benutzer möchte zwischen den Seiten navigieren können
- **Gegeben** Der Benutzer ist auf der Startseite 
- **Wenn** der Benutzer zu einem bestimmten Tab navigieren möchte
- **Dann** klickt er auf diesen Tab 
- **Und** gelangt zu der Seite 
- **Auch** kann er von dort aus weiter navigieren zu jeder Seite 

Die Navbar ist ein teil des Header und ist in jeder Seite sichtbar 
-----

**Als** Benutzer,
**möchte ich** eine Navbar sehen können
**damit** ich zwischen der Webseite navigieren kann.

**Comment by Bouchra-Allachi** [comment]
https://demos.creative-tim.com/navbar-with-icons/index.html

**Comment by Bouchra-Allachi** [comment]
Die Navbar muss noch angepasst werden. Die Icons sind zu sehr links !

**Comment by Ayse-Erdur** [comment]
Die Icons wurden geändert. 
Die Farbe von der Navbar muss muss geändert werden und die Abstände müssen angepasst werden.
