### ISSUE TITLE
In der Datenbank Pflanzeninformationen einfügen 

### ISSUE THREAD

**Issue by Bouchra-Allachi** [Bedrohung-der-Bienen/Transformationsfelder-Digitalisierung#16]
# Szenario:  Benutzer möchte ich alle Pflanzen und deren Information sehen können
- **Gegeben** Der Benutzer klickt auf Pflanzenkatalog
- **Wenn** der Benutzer eine Auflistung aller Pflanzen sieht
- **Dann** kann er durch Klicken auf eine Pflanze gelangen
- **Und**  alle Information dieser Pflanze einsehen
- **Auch** kann der Benutzer durch den link in Bienenwissen zu Pflanzenkatalog gelangen

Es muss in der Datenbank eine Tabelle Pflanze angelegt werden und alle Informationen müssen dort hinterlegt werden

-----

__Als__ Benutzer,
__möchte ich__ alle Informationen einer Pflanze einsehen können,
__damit__ ich genug Informationen über diese Pflanze habe.

**Comment by Bouchra-Allachi** [comment]
Datenbank umlaute werden nicht richtig angezeigt

**Comment by Ayse-Erdur** [comment]
Die Umlaute müssen in der Datenbank bei den Allgemeine Einstellungen auf "utf8mb4_german2_ci" umgeändert werden.
