### ISSUE TITLE
Benutzer möchte mehrere Bilder über die Pflanzen einsehen

### ISSUE THREAD

**Issue by Ayse-Erdur** [Bedrohung-der-Bienen/Transformationsfelder-Digitalisierung#19]
- **Gegeben** Der Benutzer ist auf dem Pflanzenkatalog angelangt.
- **Wenn** der Benutzer eine Pflanze auswählt,
- **Dann** kann er zwischen den Bildern in der Beschreibung wechseln
- **Und** kann sich entscheiden, ob die Pflanze ihm gefällt.
- 
**Als** Benutzer,
**möchte ich** mehrere Bilder zu einer bestimmte Pflanze einsehen können, 
**damit** ich weiß wie die Pflanze aussieht und diese in meinem Garten einsäen kann. 

Szenario 1: Benutzer kann auf der Startseite die aktuelle Pflanze, die eingesät werden kann anklicken. Somit ist wird die Pflanze angezeigt.
Szenario 2: Benutzer kann über die Bienenwissen die Pflanzen öffnen und bekommt die Pflanzen angezeigt.
Szenario 3: Benutzer kann das Pflanzenkatalog öffnen, sich eine Pflanze aussuchen und mehrere Bilder einsehen.
Szenario 4: Benutzer kann eine Pflanzen über das Aussaatkalender anzeigen lassen und dazu mehrere Bilder einsehen.

**Comment by Bouchra-Allachi** [comment]
Die Bilder müssen aus der Datenbank exportiert werden und in einem Ordner gepackt werden, da Backend nicht funktioniert und die Bilder nicht aus der Datenbank ausgelesen werden können!
