### ISSUE TITLE
Benutzer soll sich registrieren können

### ISSUE THREAD

**Issue by Moosgloeckchen** [Bedrohung-der-Bienen/Transformationsfelder-Digitalisierung#2]
# Szenario:  Benutzer soll sich registrieren können
- **Gegeben** Der Benutzer ist auf der Startseite angelangt
- **Wenn** sich der Benutzer registrieren möchte
- **Dann** klickt er auf den Login Tab in der Navigation
- **Und** es öffnet sich eine Registrierungsseite
- **Und** der Nutzer registriert sich mit email und passwort

-----

__Als__ Benutzer,
__möchte ich__ mich registrieren können
__damit__ ich mich einloggen kann.

__Szenatio 1__: Benutzer kann sich registieren.
__Szenario 2__: Registrierung schlägt fehl.

**Comment by Bouchra-Allachi** [comment]
Benutzer kann sich registrieren, jedoch kann er sich auch registrieren, wenn nicht alles eingegeben ist. If-Anweisung muss kontrolliert werden. Es wird kein Fehler ausgegeben!
