### ISSUE TITLE
Zurückbuttons einfügen

### ISSUE THREAD

**Issue by Ayse-Erdur** [Bedrohung-der-Bienen/Transformationsfelder-Digitalisierung#26]
Zwischen den Seiten soll es möglich sein hin und her zu steuern. Aus diesem Grund sind Zurückbuttons notwendig.

**Als** Benutzer,
**möchte** ich mit einem Klick auf eine vorherige Seite zurückkehren können
**damit** ich in der Webanwendung schnell navigieren kann.

Szenario 1: Der Benutzer klickt auf das "Zurückbutton", um schnell auf die vorherige Seite zu gelangen.

**Comment by Bouchra-Allachi** [comment]
Wurden alle zurück Buttons eingefügt und funktionieren diese?
