### ISSUE TITLE
Navigation einstellen

### ISSUE THREAD

**Issue by babakmehrabipour** [Bedrohung-der-Bienen/Transformationsfelder-Digitalisierung#36]
Navigation so einstellen, dass alle verfügbaren Pflanzen in der Datenbak für den Benutzer aufgelistet sind.

Senario 1: als Benutzer möchte ich während suche nach einer Pflanze, alle Pflanzen für bessere überblick aufgelistet werden.

**Comment by Bouchra-Allachi** [comment]
hat ayse schon geschrieben muss gelöscht werden
